// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// CreateEventRequest defines model for CreateEventRequest.
type CreateEventRequest struct {
	// Description Длинный текст описания (опционально)
	Description *string `json:"description,omitempty"`

	// Duration Длительность события в секундах
	Duration int64 `json:"duration"`

	// NotifyBefore За сколько времени высылать уведомление в секундах (опционально)
	NotifyBefore *int64 `json:"notify_before,omitempty"`

	// StartTime Дата и время начала события
	StartTime time.Time `json:"start_time"`

	// Title Короткий текст заголовка
	Title string `json:"title"`

	// UserId ID пользователя, владельца события
	UserId int64 `json:"user_id"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	// Error Описание ошибки
	Error string `json:"error"`
}

// EventListResponse defines model for EventListResponse.
type EventListResponse struct {
	// Events Список событий
	Events []EventResponse `json:"events"`
}

// EventResponse defines model for EventResponse.
type EventResponse struct {
	// Description Длинный текст описания
	Description *string `json:"description,omitempty"`

	// Duration Длительность события в секундах
	Duration int64 `json:"duration"`

	// Id Уникальный идентификатор события
	Id openapi_types.UUID `json:"id"`

	// NotifyBefore За сколько времени высылать уведомление в секундах
	NotifyBefore *int64 `json:"notify_before,omitempty"`

	// StartTime Дата и время начала события
	StartTime time.Time `json:"start_time"`

	// Title Короткий текст заголовка
	Title string `json:"title"`

	// UserId ID пользователя, владельца события
	UserId int64 `json:"user_id"`
}

// UpdateEventRequest defines model for UpdateEventRequest.
type UpdateEventRequest struct {
	// Description Длинный текст описания (опционально)
	Description *string `json:"description,omitempty"`

	// Duration Длительность события в секундах
	Duration int64 `json:"duration"`

	// NotifyBefore За сколько времени высылать уведомление в секундах (опционально)
	NotifyBefore *int64 `json:"notify_before,omitempty"`

	// StartTime Дата и время начала события
	StartTime time.Time `json:"start_time"`

	// Title Короткий текст заголовка
	Title string `json:"title"`

	// UserId ID пользователя, владельца события
	UserId int64 `json:"user_id"`
}

// CreateEventJSONRequestBody defines body for CreateEvent for application/json ContentType.
type CreateEventJSONRequestBody = CreateEventRequest

// UpdateEventJSONRequestBody defines body for UpdateEvent for application/json ContentType.
type UpdateEventJSONRequestBody = UpdateEventRequest
