[logger]
level = "DEBUG"

[database]
dsn = "postgres://calendar:calendar@postgres:5432/calendar?sslmode=disable"

[kafka]
brokers = ["kafka:9092"]
topic = "notifications"

[scheduler]
scan_interval = "1m"
